# Temperature controls the action distribution:
# - temp < 1.0 -> Lower entropy distribution
# - temp == 1.0 -> Use original action distribution
# - temp > 1.0 -> Higher entropy distribution
main_action_temperature: 1.0
sap_action_temperature: 1.0
